### ISSUE TITLE
Corrupt JPEG data in CameraNode

### ISSUE THREAD

**Issue by fzadow** [libavg/libavg#782] opened 2016-06-06 11:05 UTC
With JPEG selected as pixelformat for a CameraNode, I'm getting these errors output to the console (with one error line per frame):

```
Corrupt JPEG data: 1 extraneous bytes before marker 0xd4
Corrupt JPEG data: 2 extraneous bytes before marker 0xd0
Corrupt JPEG data: 4 extraneous bytes before marker 0xd7
Corrupt JPEG data: 1 extraneous bytes before marker 0xd1
Corrupt JPEG data: 3 extraneous bytes before marker 0xd5
Corrupt JPEG data: 3 extraneous bytes before marker 0xd4
[...]
```

I'm using a [Logitech C270 USB Webcam](http://www.logitech.com/en-roeu/product/hd-webcam-c270) and calling `./avg_showcamera.py  --driver=video4linux --device=/dev/video0 --pixformat=JPEG`

The images _seem_ to be fine though.

Any way to fix this? Or is it just my webcam being stupid?
Thanks! Felix
#733

@scotty007

**Comment by uzadow** [comment] 2018-03-09 09:53
Closing because not reproducible & old. 

Feel free to re-open with more info.

**Closed by uzadow** 2018-03-09 09:53 UTC
