### ISSUE TITLE
Libavg for windows console application

### ISSUE THREAD

**Issue by Pavi-thra** [libavg/libavg#625] opened 2015-03-23 10:04 UTC
Hi

I am new to libavg and I want to know whether Libavg can be used as media framework for a windows console application. Is there any possibility ?

**Comment by uzadow** [comment] 2015-03-23 20:54
Closing, since this is not a bug report. Feel free to ask your question in the forum: https://www.libavg.de/site/projects/libavg/boards/2.

**Closed by uzadow** 2015-03-23 20:54 UTC
