### ISSUE TITLE
testImageCompression crashes with Arithmetic exception

### ISSUE THREAD

**Issue by niun** [libavg/libavg#671] opened 2015-06-17 14:01 UTC
Tests are running with a few warnings `Unable to set display gamma` but then crashing at `testImageCompression (ImageTest.ImageTestCase) ...` without showing `ok` or `fail`.

A window opens with the title `python.exe`. It says *"python.exe funktioniert nicht mehr"* (german for *python.exe does not work anymore*).

**Test-System:**

* Core i5-3340 CPU (using internal Intel HD Graphics 2500)
* Windows 7 SP1 64 Bit.
* Python 2.7.10 x86
* Add C:\Python27\scripts to the PATH

**What I did:**

* Installed libavg with libavg-1.8.1.win32.exe
* Installed CMU 1394 Digital Camera Driver (1394camera646.exe)
* run tests. => crashes at `testImageCompression`. See [pastebin](http://pastebin.com/HnzpBj6m) for full output.
* run in gdb => crashes with

        Program received signal SIGFPE, Arithmetic exception.
        0x05476e49 in ig7icd32!DrvSetCallbackProcs () from C:\Windows\SysWOW64\ig7icd32.dll
  see [gdb pastebin](http://pastebin.com/vC5MBHr3) for full output.

**Comment by uzadow** [comment] 2015-06-17 14:17
Closing this because it's a duplicate.
Still, I'd like to find the cause. Could you try to get a stack trace and add it as comment to #483?
(I'm not sure how well gdb works under windows, but try entering 'bt' at the gdb prompt. Alternatively, start the tests under visual studio and open a stack trace window.)

**Closed** 2015-06-17 14:18 UTC
Labels: duplicate
