### ISSUE TITLE
Compiling for Raspberry Pi 2

### ISSUE THREAD

**Issue by cstranex** [libavg/libavg#612] opened 2015-03-07 10:13 UTC
If I checkout the latest version of libavg from git:
./bootstrap
./configure --enable-rpi
make

The build eventually fails with:
  CXXLD  testgpu
/usr/bin/ld: ./.libs/libgraphics.a(BCMDisplay.o): undefined reference to symbol 'vc_dispmanx_element_add'
//opt/vc/lib/libbcm_host.so: error adding symbols: DSO missing from command line
collect2: ld returned 1 exit status
Makefile:668: recipe for target 'testgpu' failed

Any suggestions to make compiling work?

**Comment by uzadow** [comment] 2015-03-07 14:35
You had this running with an older libavg version, right? Are you cross-compiling or compiling on the RPi itself?

I spent a bit of time working on this last week, but didn't get to the point where I could reproduce the bug - I'll see what I can do next week.

**Comment by cstranex** [comment] 2015-03-07 14:59
I haven't tried another version of libavg but I see the repository does have libavg 1.7 in it.

This is compiling on the RPi itself, I can try cross compile if it would make a difference but I'd imagine not. I also haven't tried on the original RPi 1.

**Comment by uzadow** [comment] 2015-03-08 09:32
The newest release version is 1.8.2. You could try with that to narrow it down. If that succeeds, a git bisect would be really helpful. If it doesn't, there's a good chance it's a configuration issue.

**Comment by cstranex** [comment] 2015-03-08 15:08
So far I've tested the 1.8.2, 1.8.1 and 1.8.0 releases.

All of them have failed to build in the same place with the same error

**Comment by klemmster** [comment] 2015-03-09 07:32
This might be related to:
[Raspberry Firmware 290](https://github.com/raspberrypi/firmware/issues/290)

**Comment by uzadow** [comment] 2015-03-09 07:50
Good find. 

@cstranex, it looks like the link above contains a few linker flags that need to be set for newer versions of the RPi Linux kernel. They go in src/graphics/Makefile.am, in the if `ENABLE_RPI` section.

**Comment by cstranex** [comment] 2015-03-09 16:09
Adding "-lbcm_host" to the Makefile gets past the testgpu file. The change must also be made in src/video/Makefile.am otherwise compiling 'testvideo' fails. "-lbcm_host -lpthread" must be added to src/player/Makefile.am

1.8.2 seems to be building after that

**Comment by uzadow** [comment] 2015-03-09 16:10
Great!
Can you send us a patch (using git diff or similar) for your changes?

**Comment by cstranex** [comment] 2015-03-09 18:57
I'll send patch shortly, but have just seen it failed here:

  CXX    ColorNode.lo
ColorNode.cpp: In function 'int __gthread_active_p()':
ColorNode.cpp:152:1: internal compiler error: Segmentation fault
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.6/README.Bugs> for instructions.
Preprocessed source stored into /tmp/ccmKzyWu.out file, please attach this to your bugreport.

**Comment by uzadow** [comment] 2015-03-09 19:43
Hm... first of all, thanks for the patch, I'm merging it right now.
It looks like the segfault might be a result of an out of memory condition. If that's the case, compiling with less optimization (-O2 instead of -O3) or cross-compiling are the options you have. I'd suggest cross-compiling anyway, because that will bring your build time down to about 20 mins. We have (possibly outdated) instructions here: https://www.libavg.de/site/projects/libavg/wiki/RPI

**Comment by cstranex** [comment] 2015-03-10 08:57
Cool, I've been trying the cross compilation but the xecdesign kernel is too old for the newest Raspbian image but will let you know if it eventually works. Thanks for the help

**Comment by uzadow** [comment] 2015-03-19 19:40
We have a report that compiling on the RPi 2 works: #623. @cstranex, can you try to find out what's different between your two compiles?

**Comment by cstranex** [comment] 2015-03-21 15:40
Strange, I wonder if it's a difference between the versions of Raspbian. I will let you know if I make progress

**Comment by uzadow** [comment] 2015-03-27 09:31
We now have a second person that's compiled libavg on the RPi 2 successfully - see #627. I assume this is a configuration issue and am therefore closing the report.

**Closed by uzadow** 2015-03-27 09:31 UTC
Labels: Bug, help wanted, Platform
