### ISSUE TITLE
testvideo fails [ffmpeg]

### ISSUE THREAD

**Issue by klemmster** [libavg/libavg#535] opened 2014-09-24 08:29 UTC
libavg version: d1941ec4c983181dcc5e5d92cc7c142b82a57224 (master)
ffmpeg version: 2.4.1-1
Archlinux: 3.16.3-1-ARCH
nvidia: nvidia 340.32-2
CPU: Intel(R) Core(TM) i7 CPU 950  @ 3.07GHz

Testvideo-output: https://gist.github.com/klemmster/ed3994304b405e5a3668

**Comment by uzadow** [comment] 2015-03-09 22:40
Can be reproduced with Ubuntu 14.10.

**Comment by uzadow** [comment] 2015-03-12 18:57
I just got confirmation from one of the libav developers that the interface we've been using for VDPAU acceleration has been removed completely from libav and ffmpeg and replaced by a new interface. Here's his mail: https://lists.libav.org/pipermail/libav-tools/2015-March/000550.html

This means that if we want hardware-accelerated video on NVidia machines, someone has to rewrite the complete support :-/.

**Comment by klemmster** [comment] 2015-03-13 08:17
Maybe it would be most useful to revive https://github.com/libavg/libavg/tree/libavg_vaapi, 
as this would cover nvidia, amd and intel instead of only nvidia. (at least according to [ArchlinuxWiki](https://github.com/libavg/libavg/tree/libavg_vaapi))

**Comment by uzadow** [comment] 2015-03-13 09:26
Hm - could you fix the link to ArchLinuxWiki? It points to the libavg tree...

**Comment by klemmster** [comment] 2015-03-13 09:28
Ahh sorry. It's fixed.

**Comment by uzadow** [comment] 2015-03-13 09:29
Sounds like a good idea. Anyone up for doing the work?

**Comment by uzadow** [comment] 2015-03-13 21:13
I just realized we're talking about two different bugs here, and I've moved the Ubuntu 14.10/libav bug here: #620.
Sorry for the confusion.

**Comment by uzadow** [comment] 2015-03-13 21:14
@klemmster: Can you check if the original bug happens with ffmpeg 2.6? Because when I install current ffmpeg on Ubuntu, everything is fine.

**Comment by klemmster** [comment] 2015-03-14 09:54
The error is different now: 
```
======================================================================
FAIL: testVideoHRef (AVTest.AVTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/richy/Projects/Libavg/libavg/src/test/AVTest.py", line 239, in testVideoHRef
    testVideoBroken()
  File "/home/richy/Projects/Libavg/libavg/src/test/AVTest.py", line 233, in testVideoBroken
    self.assertRaises(avg.Exception, node.play)
AssertionError: Exception not raised

------
```

Sorry, I'm lacking the time to look into this deeper right now.

**Comment by uzadow** [comment] 2015-03-14 10:21
Thanks @klemmster. 
I'm closing this bug as 'fixed upstream' and opening a new one with the new error to reduce confusion.

**Comment by uzadow** [comment] 2015-03-14 10:21
New bug: #621

**Closed by uzadow** 2015-03-14 10:21 UTC
Labels: Bug, Platform, video
