### ISSUE TITLE
testImageCompression fails under Win7/Intel HD Graphics

### ISSUE THREAD

**Issue by libavgIssueImporter** [libavg/libavg#483] opened 2014-05-23 11:33 UTC
_this ticket is transfered from former bug tracking system_

Running

<pre>
./Test.py image testImageCompression
</pre>

terminates with a division by zero error in the graphics driver.

---

**author:** [uzadow](https://github.com/uzadow)
**created:** 2014/02/25 13:47:41 +0100
**assigned to:** None
**priority:** Normal
**project:** libavg

**Comment by uzadow** [comment] 2015-06-17 14:19
@niun, @kuhfisch: It would be great to have a stacktrace.

**Comment by uzadow** [comment] 2015-06-17 16:33
This doesn't happen with all Intel GPUs under windows. 
Reproducible under:
- Intel HD Graphics 2500, Win 7.
- NVidia GeForce GT 630M, Win 7.

Not reproducible:
- most NVidia drivers, Win 7 and 8.1.
- Intel HD 4600, Win 8.1.

**Comment by niun** [comment] 2015-07-07 11:59
@uzadow sorry, I am a Windows noob. A complete stacktrace seems to be complicated. Entering `bt` into `gdb` gives not more informations than I posted in #671 . Would need to have python compiled with debug symbols and py-bt python extension for gdb. With Visual Studio, I am completely lost. You can somehow load an extra python debuggin symbols package into your project but than I cannot find a way to run a python script in that context. Does someone have docs about either of the two topics? Than I could look further into this.

**Comment by uzadow** [comment] 2015-07-07 12:21
To get a stacktrace under windows, start the program (in this case, python.exe with the name of the python script as parameters) under visual studio. That involves changing the project settings of, e.g., the wrapper project (right-click on project->Properties->Debugging, 'Command' is python and 'Command Arguments' is the python script. Then right-click on the project again, select 'Set as startup project' and start the debugger.

There's no need to register the python debugging symbols.

**Comment by uzadow** [comment] 2018-03-09 09:53
Closing because not reproducible & old. 

Feel free to re-open with more info.

**Closed by uzadow** 2018-03-09 09:53 UTC
Labels: Bug, Platform
